version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.spotbugs:spotbugs-maven-plugin
    versions:
    - 4.2.0
    - 4.2.2
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
  - dependency-name: com.amashchenko.maven.plugin:gitflow-maven-plugin
    versions:
    - 1.15.1
  - dependency-name: pl.project13.maven:git-commit-id-plugin
    versions:
    - 4.0.3
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-xml
    versions:
    - 2.11.3
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.11.3
