language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

notifications:
  slack:
    on_success: always
    on_failure: always
  email:
    - leonardo.falco@outlook.com

cache:
  directories:
    - $HOME/.m2