language: java
jdk:
  - openjdk9
  - openjdk8

notifications:
  slack:
    on_success: always
    on_failure: always
  email:
    - leonardo.falco@outlook.com

cache:
  directories:
    - $HOME/.m2

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN